# vim ft=yaml
language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip pytest
  - pip install runipy coveralls pytest-cov
  - pip install -e '.'

script:
  - py.test --pyargs grabbit --cov-report term-missing --cov=grabbit

after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  skip_cleanup: true
  on:
    tags: true
